name: lost_and_found_app
description: "Lost and found app."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true